
services:
  ngircd:
    image: lscr.io/linuxserver/ngircd:latest
    container_name: ngircd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./ngircd:/config
    ports:
      - 6667:6667
    restart: unless-stopped


  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"  # Web client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./thelounge:/config
    depends_on:
      - ngircd
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - thelounge