services:
  ngircd:
    image: lscr.io/linuxserver/ngircd:latest
    container_name: ngircd
    env_file:
      - ./.irc.env
    volumes:
      - ./ngircd:/config
    ports:
      - "${IRC_PORT}:${IRC_PORT}"
    restart: unless-stopped
    networks:
      - irc-net

  thelounge:
    image: thelounge
    build:
      context: ./thelounge
      dockerfile: thelounge.Dockerfile
    container_name: thelounge
    env_file:
      - ./.irc.env
    ports:
      - "${THELOUNGE_PORT}:${THELOUNGE_PORT}"  # Web client
    volumes:
      - ./thelounge/config:/config
      - ./thelounge/themes/abyss.css:/app/thelounge/public/themes/default.css
      - ./thelounge/themes/morning.css:/app/thelounge/public/themes/morning.css
      - ./thelounge/assets/theodore.jpg:/app/thelounge/public/img/theodore.jpg
    depends_on:
      - ngircd
    restart: unless-stopped
    networks:
      - irc-net

  nginx:
    image: nginx:latest
    container_name: nginx
    env_file:
      - ./.irc.env
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - thelounge
    networks:
      - irc-net

networks:
  irc-net:
    name: ${DOCKER_NETWORK}
    external: true
